name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    
      

jobs:
  build:
    env:
      platform: "azure"
      region: "eastus"
      account: "maguilare"

    runs-on: ubuntu-latest

    steps:
    - name: "Show the message"    
      run: echo "Hello DevOps World!"

    - name: "I'm showing ENV"
      if: ${{ env.platform == 'azure' }}      
      run: |
        echo "This is the Azure value: ${{ env.platform }}"
        echo "This is de region: ${{ env.region }}"
        echo "My Account ID: ${{ env.account }}"

    - name: "Mostrando variables por defecto"
      run: |
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
        echo "GITHUB_REPOSITORY: ${{ github.repository }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"