name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Show the message"    
      run: echo "Hello DevOps World!"
