name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    
      

jobs:
  build:
    env:
      platform: "azure"
      region: "eastus"
      account: "maguilare"

    runs-on: ubuntu-latest

    steps:
    - name: "Show the message"    
      run: echo "Hello DevOps World!"

    - name: "I'm showing ENV"
      if: ${{ env.platform == 'asure' }}      
      run: |
        echo "This is the Azure value: ${{ env.platform }}"
        echo "This is de region: ${{ env.region }}"
        echo "My Account ID: ${{ env.account }}"